language: node_js #设置语言

node_js: stable #设置相应的版本

install:
  - npm install # 安装 package.json 中的插件

cache: #缓存配置
  directories:
    - node_modules

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
	- cd ./public
	- git init
	- git config user.name "ihoey"
	- git config user.email "mail@ihoey.com"
	- git add .
	- git commit -m " 这个勤奋的家伙又更新了~"
	- git push --force --quiet "https://${ihoey_blog}@${GH_REF}" master:master

branches:
	only:
		- hexo

env:
	global:
		- GH_REF: git@github.com:ihoey/blog.git
